@startuml
!define ad -[dotted]->返回响应;

title 项目构建
|u|
start
floating note
# 用户忘记密码时会调用此接口验证
# 用户注册时会调用此接口验证
end note

:用户在注册或忘记密码界面
----
点击获取验证码;
|f|
:调用 getVerfCode 接口;
:弹出等待框;
|b|
:getVerfCode 接口
----
1. 输入判断
2. 发送验证码,本地缓存保存验证码时间为 1 分钟
3. 返回调用结果

上面步骤顺序执行
**任何一个步骤失败会立即返回结果**
;
|f|
ad
:关闭等待框;
if (状态码是否为成功) then(N)
:显示对应模态框;
end;
else (Y)
:模态框提示验证码发送成功;
|u|
:用户在对应界面输入验证码;
end
endif
@enduml